### PR TITLE
(CLOUD-718) Deprecate the Puppet AWS CloudFormation face

### PR DESCRIPTION
**Pull request by gregohardy**

### CODE REVIEW

**Comment by gregohardy** [comment]
There is no public solution or it would have been added. The AWS CloudFormation templates are private at the moment and are due to be released.

**Comment by DavidS** [comment]
As discussed offline, we'll keep this one open until the replacement is released, RSN.

**Comment by gregohardy** [comment]
I'm updating the ticket to reflect this.

**Comment by gregohardy** [comment]
Added changes for Eamonn comments

**Pull request merged**
