### PR TITLE
Fixed a slew of bugs related to templates and variables...

### PR DESCRIPTION
**Pull request by nvalentine-puppetlabs**
Talked to Ryan and it seems like this work is not going to be continued but I'll submit the PR anyway.

### CODE REVIEW

**Comment by tphoney** [comment]
Ping could you please "Waiting for CLA signature by @nvalentine-puppetlabs"

**Comment by nvalentine-puppetlabs** [comment]
Puppet Labs employee and have previously signed. It won't allow me to sign again.

**Comment by tphoney** [comment]
can you squash your commits please and we can merge it.

**Comment by tphoney** [comment]
Thanks for the work you have put in to this pull request. However due to inactivity and needed the commits squashed. This pull request is being closed. If you want to re-submit this pr with the necessary changes, we will look at the new pull request.

**Pull request closed without merging**
